### ISSUE TITLE
Add limits and requests to the operator pod

### ISSUE THREAD

**Issue by tormig-softronic** [3scale/apicast-operator#122]
Currently the operator is installed without any limits and requests  on the pod which make an installation to a namespace with resource quotas impossible. The APIcast instances do have limits and requests so this appears just to be an oversight. I know you can add this to the CSV but that can only be after the operator has been installed (right?).

**Comment by eguzki** [comment]
Operator `v0.4.0' does not include, but it has been already fixed in #88 and next release (probably `v0.5.0`) will include it. Coming soon with 3scale 2.11
