### ISSUE TITLE
apicast-community-operator  not available any more ?

### ISSUE THREAD

**Issue by slawomir-jach** [3scale/apicast-operator#176]
Hi.  I'm trying deploy on Kubernetes community version of apicast operator from operatorhub.io . Looks like api is not working and is depreciated as logs said
kubectl describe  sub my-apicast-community-operator 
.......
.......
Message:                api-server resource not found installing CustomResourceDefinition apicasts.apps.3scale.net: GroupVersionKind apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition not found on the cluster. This API may have been deprecated and removed, see https://kubernetes.io/docs/reference/using-api/deprecation-guide/ for more information.

I can't find so many information about community version .

**Comment by eguzki** [comment]
K8s dropped the deprecated `apiextensions.k8s.io/v1beta1` API and the latest apicast operator community version released used that API. We plan to release a new version of the apicast operator with the ` apiextensions.k8s.io/v1` API that you should be able to deploy in latest k8s versions.

**Comment by slawomir-jach** [comment]
Hi there.  Any updates ?

**Comment by eguzki** [comment]
no news :) working hard on the 3scale 2.12 just went GA last week. I will have now some time to work on this issue
