### ISSUE TITLE
Invalid image in version 0.5.3

### ISSUE THREAD

**Issue by jonathansimas** [3scale/apicast-operator#177]
In version 0.5.3 operator is trying to pull the image 
registry.redhat.io/3scale-amp2/apicast-rhel7-operator@sha256:ccd64090b85536ddaf1b81ca07d40279c9f277b1c5911628f11d678b98dc3bad that aparently doesn't exists

**Comment by eguzki** [comment]
Fixed https://catalog.redhat.com/software/containers/3scale-amp2/apicast-rhel7-operator/5e18b97cbed8bd66f81c07d6?tag=1.14.1-14
