### ISSUE TITLE
Improve installation instructions for first-time users

### ISSUE THREAD

**Issue by gsaslis** [3scale/apicast-operator#44]
1. I tried deploying the apicast operator on an empty local k3d cluster, following the instructions in https://github.com/3scale/apicast-operator#deploy-apicast-gateway-providing-configuration-secret.

I can see that all the pods, etc. are up, but how can I test that "it worked" ? 
Do you think we could add a smoke test there at the end? (e.g. some `curl` that returns back an expected response?)

**Comment by eguzki** [comment]
#50 fixes
